listener 8883
# cafile /mosquitto/config/ssl/origin.pem       # trust chain (CF Origin cert works)
# server cert
certfile /mosquitto/config/ssl/origin.pem
# private key
keyfile /mosquitto/config/ssl/origin.key
# minium version
tls_version tlsv1.1
allow_anonymous false
password_file /mosquitto/data/passwd
