listener 8883
cafile /mosquitto/config/ssl/origin.pem       # trust chain (CF Origin cert works)
certfile /mosquitto/config/ssl/origin.pem     # server cert
keyfile /mosquitto/config/ssl/origin.key      # private key
tls_version tlsv1.2
allow_anonymous false
password_file /mosquitto/data/passwd